// ─── Constants ───

export const API_URLS = {
  NEWS_RSS: 'https://news.google.com/rss/search?q=',
  WEATHER: 'https://api.open-meteo.com/v1/forecast',
  AQI: 'https://api.waqi.info/feed/',
  EARTHQUAKE: 'https://earthquake.usgs.gov/fdsnws/event/1/query',
  RAILWAY: 'https://indianrailapi.com/api/v2',
  IRCTC_PROXY: '/api/railway',
} as const;

export const INDIA_BOUNDS = {
  center: [22.5, 82.0] as [number, number],
  zoom: 5,
  minZoom: 4,
  maxZoom: 12,
  bounds: [[6.5, 68.0], [37.0, 97.5]] as [[number, number], [number, number]],
};

export const METRO_CITIES = [
  { name: 'Delhi Metro', city: 'Delhi', lines: 12, stations: 288, dailyRidership: '5.5M', lat: 28.6139, lng: 77.2090, color: '#ff6b35' },
  { name: 'Mumbai Metro', city: 'Mumbai', lines: 3, stations: 46, dailyRidership: '0.8M', lat: 19.0760, lng: 72.8777, color: '#00d4aa' },
  { name: 'Bengaluru Metro', city: 'Bengaluru', lines: 2, stations: 62, dailyRidership: '0.7M', lat: 12.9716, lng: 77.5946, color: '#a855f7' },
  { name: 'Chennai Metro', city: 'Chennai', lines: 2, stations: 40, dailyRidership: '0.3M', lat: 13.0827, lng: 80.2707, color: '#4ecdc4' },
  { name: 'Kolkata Metro', city: 'Kolkata', lines: 2, stations: 32, dailyRidership: '0.6M', lat: 22.5726, lng: 88.3639, color: '#ffe66d' },
  { name: 'Hyderabad Metro', city: 'Hyderabad', lines: 3, stations: 57, dailyRidership: '0.5M', lat: 17.3850, lng: 78.4867, color: '#06b6d4' },
  { name: 'Kochi Metro', city: 'Kochi', lines: 1, stations: 25, dailyRidership: '0.07M', lat: 9.9312, lng: 76.2673, color: '#f43f5e' },
  { name: 'Lucknow Metro', city: 'Lucknow', lines: 1, stations: 21, dailyRidership: '0.08M', lat: 26.8467, lng: 80.9462, color: '#22c55e' },
  { name: 'Jaipur Metro', city: 'Jaipur', lines: 1, stations: 11, dailyRidership: '0.03M', lat: 26.9124, lng: 75.7873, color: '#eab308' },
  { name: 'Nagpur Metro', city: 'Nagpur', lines: 2, stations: 36, dailyRidership: '0.05M', lat: 21.1458, lng: 79.0882, color: '#ec4899' },
  { name: 'Pune Metro', city: 'Pune', lines: 2, stations: 30, dailyRidership: '0.12M', lat: 18.5204, lng: 73.8567, color: '#14b8a6' },
  { name: 'Ahmedabad Metro', city: 'Ahmedabad', lines: 2, stations: 32, dailyRidership: '0.1M', lat: 23.0225, lng: 72.5714, color: '#f97316' },
];

export const RAILWAY_ZONES = [
  { code: 'CR', name: 'Central Railway', hq: 'Mumbai', color: '#ef4444' },
  { code: 'ER', name: 'Eastern Railway', hq: 'Kolkata', color: '#3b82f6' },
  { code: 'NR', name: 'Northern Railway', hq: 'Delhi', color: '#22c55e' },
  { code: 'NER', name: 'North Eastern Railway', hq: 'Gorakhpur', color: '#a855f7' },
  { code: 'NFR', name: 'Northeast Frontier Railway', hq: 'Guwahati', color: '#06b6d4' },
  { code: 'SR', name: 'Southern Railway', hq: 'Chennai', color: '#f97316' },
  { code: 'SCR', name: 'South Central Railway', hq: 'Hyderabad', color: '#ec4899' },
  { code: 'SER', name: 'South Eastern Railway', hq: 'Kolkata', color: '#eab308' },
  { code: 'WR', name: 'Western Railway', hq: 'Mumbai', color: '#14b8a6' },
  { code: 'SWR', name: 'South Western Railway', hq: 'Hubballi', color: '#8b5cf6' },
  { code: 'NWR', name: 'North Western Railway', hq: 'Jaipur', color: '#f43f5e' },
  { code: 'WCR', name: 'West Central Railway', hq: 'Jabalpur', color: '#84cc16' },
  { code: 'NCR', name: 'North Central Railway', hq: 'Prayagraj', color: '#0ea5e9' },
  { code: 'SECR', name: 'South East Central Railway', hq: 'Bilaspur', color: '#d946ef' },
  { code: 'ECR', name: 'East Central Railway', hq: 'Hajipur', color: '#fb923c' },
  { code: 'ECoR', name: 'East Coast Railway', hq: 'Bhubaneswar', color: '#2dd4bf' },
  { code: 'KRCL', name: 'Konkan Railway', hq: 'Navi Mumbai', color: '#c084fc' },
];

export const STOCK_INDICES = [
  { name: 'SENSEX', exchange: 'BSE', description: 'BSE Sensitive Index (30 stocks)' },
  { name: 'NIFTY 50', exchange: 'NSE', description: 'NSE Nifty 50 Index' },
  { name: 'NIFTY BANK', exchange: 'NSE', description: 'Bank sector index' },
  { name: 'NIFTY IT', exchange: 'NSE', description: 'IT sector index' },
  { name: 'NIFTY PHARMA', exchange: 'NSE', description: 'Pharma sector index' },
  { name: 'NIFTY AUTO', exchange: 'NSE', description: 'Auto sector index' },
  { name: 'NIFTY MIDCAP', exchange: 'NSE', description: 'Mid-cap index' },
  { name: 'INDIA VIX', exchange: 'NSE', description: 'Volatility index' },
];

export const NEWS_CATEGORIES = [
  { id: 'politics', label: 'Politics', icon: '🏛️', query: 'India politics parliament' },
  { id: 'economy', label: 'Economy', icon: '📊', query: 'India economy GDP RBI' },
  { id: 'defense', label: 'Defense', icon: '🛡️', query: 'India defense military DRDO' },
  { id: 'technology', label: 'Technology', icon: '💻', query: 'India technology startup IT' },
  { id: 'climate', label: 'Climate', icon: '🌦️', query: 'India weather monsoon IMD' },
  { id: 'health', label: 'Health', icon: '🏥', query: 'India health AIIMS ICMR' },
  { id: 'transport', label: 'Transport', icon: '🚆', query: 'India railways metro transport' },
  { id: 'space', label: 'Space', icon: '🚀', query: 'ISRO India space satellite' },
  { id: 'education', label: 'Education', icon: '📚', query: 'India education IIT NEET' },
  { id: 'agriculture', label: 'Agriculture', icon: '🌾', query: 'India agriculture farming MSP' },
  { id: 'energy', label: 'Energy', icon: '⚡', query: 'India energy solar power grid' },
  { id: 'disaster', label: 'Disasters', icon: '🌊', query: 'India flood earthquake cyclone disaster' },
];

export const MAJOR_AIRPORTS = [
  { code: 'DEL', name: 'Indira Gandhi International', city: 'Delhi', lat: 28.5562, lng: 77.1000 },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj', city: 'Mumbai', lat: 19.0896, lng: 72.8656 },
  { code: 'BLR', name: 'Kempegowda International', city: 'Bengaluru', lat: 13.1979, lng: 77.7063 },
  { code: 'MAA', name: 'Chennai International', city: 'Chennai', lat: 12.9941, lng: 80.1709 },
  { code: 'HYD', name: 'Rajiv Gandhi International', city: 'Hyderabad', lat: 17.2403, lng: 78.4294 },
  { code: 'CCU', name: 'Netaji Subhas Chandra Bose', city: 'Kolkata', lat: 22.6520, lng: 88.4463 },
  { code: 'COK', name: 'Cochin International', city: 'Kochi', lat: 10.1520, lng: 76.4019 },
  { code: 'GOI', name: 'Manohar International', city: 'Goa', lat: 15.3808, lng: 73.8314 },
  { code: 'AMD', name: 'Sardar Vallabhbhai Patel', city: 'Ahmedabad', lat: 23.0771, lng: 72.6347 },
  { code: 'PNQ', name: 'Pune Airport', city: 'Pune', lat: 18.5822, lng: 73.9197 },
  { code: 'JAI', name: 'Jaipur International', city: 'Jaipur', lat: 26.8242, lng: 75.8122 },
  { code: 'LKO', name: 'Chaudhary Charan Singh', city: 'Lucknow', lat: 26.7606, lng: 80.8893 },
  { code: 'PAT', name: 'Jay Prakash Narayan', city: 'Patna', lat: 25.5913, lng: 85.0880 },
  { code: 'BBI', name: 'Biju Patnaik International', city: 'Bhubaneswar', lat: 20.2444, lng: 85.8178 },
  { code: 'VTZ', name: 'Visakhapatnam Airport', city: 'Visakhapatnam', lat: 17.7213, lng: 83.2245 },
  { code: 'IXC', name: 'Chandigarh Airport', city: 'Chandigarh', lat: 30.6735, lng: 76.7885 },
  { code: 'ATQ', name: 'Sri Guru Ram Dass Jee', city: 'Amritsar', lat: 31.7096, lng: 74.7973 },
  { code: 'GAU', name: 'Lokpriya Gopinath Bordoloi', city: 'Guwahati', lat: 26.1061, lng: 91.5859 },
  { code: 'NAG', name: 'Dr. Babasaheb Ambedkar', city: 'Nagpur', lat: 21.0922, lng: 79.0472 },
  { code: 'IDR', name: 'Devi Ahilyabai Holkar', city: 'Indore', lat: 22.7218, lng: 75.8011 },
  { code: 'SXR', name: 'Sheikh ul-Alam International', city: 'Srinagar', lat: 33.9871, lng: 74.7742 },
  { code: 'IXR', name: 'Birsa Munda Airport', city: 'Ranchi', lat: 23.3143, lng: 85.3217 },
  { code: 'TRV', name: 'Trivandrum International', city: 'Thiruvananthapuram', lat: 8.4821, lng: 76.9199 },
  { code: 'CCJ', name: 'Calicut International', city: 'Kozhikode', lat: 11.1368, lng: 75.9553 },
  { code: 'IXM', name: 'Madurai Airport', city: 'Madurai', lat: 9.8345, lng: 78.0934 },
  { code: 'VNS', name: 'Lal Bahadur Shastri', city: 'Varanasi', lat: 25.4524, lng: 82.8593 },
  { code: 'IXB', name: 'Bagdogra Airport', city: 'Siliguri', lat: 26.6812, lng: 88.3286 },
  { code: 'RPR', name: 'Swami Vivekananda Airport', city: 'Raipur', lat: 21.1804, lng: 81.7388 },
  { code: 'UDR', name: 'Maharana Pratap Airport', city: 'Udaipur', lat: 24.6177, lng: 73.8961 },
  { code: 'GWL', name: 'Rajmata Vijaya Raje Scindia', city: 'Gwalior', lat: 26.2933, lng: 78.2278 },
  { code: 'NMIA', name: 'Navi Mumbai International', city: 'Navi Mumbai', lat: 18.8489, lng: 73.0192 },
  { code: 'DEP', name: 'Devi Ahilya Bai Holkar', city: 'Indore', lat: 22.7218, lng: 75.8011 },
  { code: 'BDQ', name: 'Vadodara Airport', city: 'Vadodara', lat: 22.3362, lng: 73.2263 },
  { code: 'RAJ', name: 'Rajkot Airport', city: 'Rajkot', lat: 22.3092, lng: 70.7795 },
  { code: 'JDH', name: 'Jodhpur Airport', city: 'Jodhpur', lat: 26.2511, lng: 73.0489 },
  { code: 'IXJ', name: 'Jammu Airport', city: 'Jammu', lat: 32.6891, lng: 74.8374 },
  { code: 'DED', name: 'Jolly Grant Airport', city: 'Dehradun', lat: 30.1897, lng: 78.1803 },
  { code: 'IXA', name: 'Maharaja Bir Bikram', city: 'Agartala', lat: 23.8870, lng: 91.2404 },
  { code: 'IMF', name: 'Imphal Airport', city: 'Imphal', lat: 24.7620, lng: 93.8967 },
  { code: 'DIB', name: 'Dibrugarh Airport', city: 'Dibrugarh', lat: 27.4839, lng: 95.0169 },
  { code: 'CJB', name: 'Coimbatore International', city: 'Coimbatore', lat: 11.0300, lng: 77.0434 },
  { code: 'TRZ', name: 'Tiruchirappalli International', city: 'Tiruchirappalli', lat: 10.7654, lng: 78.7097 },
  { code: 'MNG', name: 'Mangalore International', city: 'Mangalore', lat: 12.9614, lng: 74.8901 },
  { code: 'HBX', name: 'Hubli Airport', city: 'Hubli', lat: 15.3617, lng: 75.0849 },
  { code: 'STV', name: 'Surat Airport', city: 'Surat', lat: 21.1141, lng: 72.7418 },
  { code: 'AGR', name: 'Agra Airport', city: 'Agra', lat: 27.1558, lng: 77.9609 },
  { code: 'BHO', name: 'Raja Bhoj Airport', city: 'Bhopal', lat: 23.2875, lng: 77.3374 },
];
